### ISSUE TITLE
Output Device Low/High command ignore_case flag ignored

### ISSUE THREAD

**Issue by dominik013** [ulno/ulnoiot-upy#10]
When creating an output for example:
`valve = output("valve", d2, "On", "Off", True)`
and testing the output with:
`valve.evaluate("On")`
the command could not be interpreted, `ignore_case` flag seems to be ignored.

**Comment by ulno** [comment]
2129eb3b0fc63ba0d66db9c55277e55f07327d91 fixes this, make sure to ulnoiot upgrade and flash.
