### ISSUE TITLE
Suggestion: Make it possible to clear the display and set a new text with one command

### ISSUE THREAD

**Issue by dominik013** [ulno/ulnoiot-upy#15]
It would be really cool if we could clear the display's text and set a new one with just a single mqtt command, like:
`display.evaluate("&&clear Hello World")`
This would really simplify and prettify the process of setting text with node-red since we would not have to do a clear with a following delayed set.

**Comment by ulno** [comment]
Possible since 3e7e34309a784bbbf61c79e4069f802dbdcba8d3
