### ISSUE TITLE
Code has multiple PEP8 issues, showing novices a bad example of how to write in Python

### ISSUE THREAD

**Issue by pfalcon** [ulno/ulnoiot-upy#22]
From README:

> It has a special focus on education and is intended to support classes to teach Internet of Things (IoT) and home automation.

It's very worthy a goal. However, please take a chance to do it right from the beginning - by following the the official Python code style, PEP8: https://www.python.org/dev/peps/pep-0008/ . Looking thru the code, it has multiple issues with that, and thus teaches novices a bad way to write Python apps (and makes it hard to work with the code for people who have more experience with Python).

As an example,

~~~
input("up",d1,0,1)
~~~

should be

~~~
input("up", d1, 0, 1)
~~~

per PEP8 (arguments clearly separated by spaces).

**Comment by ulno** [comment]
Hi pfalcon,
thanks for taking a time to take a look. I skip lots of blanks in the code as it significantly reduces the size of the python source files and immensely increases the chance of the files being compiled in micropython as memory is very small. I agree with you that I should probably apply proper formatting as soon as the code moves to frozen section in the firmware, but I am also running there out of space. Maybe I should pre-process proper python code first similar to tries in this script (https://github.com/ulno/ulnoiot/blob/master/bin/shrink_python using pyminify and unexpand) in general?

I wonder if there have been some thoughts on this in the micropython community in general -> probably should take the discussion there.

**Comment by pfalcon** [comment]
Well, I looked thru various files and IIRC, PEP8 is not followed in the files for CPython too.

> I skip lots of blanks in the code as it significantly reduces the size of the python source files and immensely increases the chance of the files being compiled in micropython as memory is very small.

Well, I doubt "significantly" and "immensely" words give the truth here. Of course, files without whitespace are smaller, but MicroPython's parser works in a streaming manner and just skips whitespace, so it unlikely affects how much memory is taken for parsing, but greatly reduces readability.

 > Maybe I should pre-process proper python code first similar to tries in this script (https://github.com/ulno/ulnoiot/blob/master/bin/shrink_python using pyminify and unexpand) in general? I wonder if there have been some thoughts on this in the micropython community in general -> probably should take the discussion there.

There was a lot of ideas during the last 3 years. In particular, idea of using source-level minimizer is very old. I used to write my own minimizer and dropped it completely after persistent bytecode was added. For a small-heap device like esp8266, you really need to go straight to frozen bytecode, because it's indeed a challenge to make enough code to run on it otherwise. I wrote down instructions how to to deploy a non-trivial app on esp8266 as the frozen bytecode, so may recommend using that as a reference: 
https://github.com/pfalcon/notes-pico/#deploying-on-embedded-micropython-targets

Of course, we need to further elaborate them to make them more streamlined, but first more people need to get familiar with using frozen bytecode in general. And it's not that hard if following the best practices, as the above instructions show.

But the first and foremost best practice to follow is writing the code in a way which is readable by the majority of the community, that's the grounds of it all. So, PEP8 please ;-).

**Comment by ulno** [comment]
Will fix while moving along and see what breaks. Feel free to make pull requests.

However, as I said, I am at the point where I doubt my whole choice of Micropython for an IoT framework and taking a closer look at rtos and Mongoose.

Maybe, having the dream of a system running on a networked microcontroller like the esp8266 which allows loading drivers for various peripherals at runtime from flash or the network and supporting lots of the standard devkit sensor's and actors is a bit ambitious (doing most of it in Python and having a very simple configuration to do it would have been another huge plus).

I definitely have to rethink very actively the use of frozen bytecode in the firmware as there is just not enough space for all the drivers I want to include - so the only chance is to load things on demand if I don't want to compile a firmware for each deployed node (and then I am probably much better of scripting something around platformio and rboot).

The example you mention also only seems to work on a firmware tree and has to be compiled and flashed later - so what is the difference of linking selected modules into the module directory?

**Comment by ulno** [comment]
I hope I caught them all now. If you still catch a bad example (there might actually be something in the old example documentation in examples), let me know and I will try to fix it quickly.
