### ISSUE TITLE
ulniot prompt issue

### ISSUE THREAD

**Issue by Ryanor** [ulno/ulnoiot-upy#8]
If the prompt command is set in the .bashrc the ulnoiot command prompt does not show up correctly and the user does not recognize he is inside the ulnoiot.

Please overwrite the prompt command in the bash file

**Comment by ulno** [comment]
6b188df3a7acf4ce574f58fe15169229fe47322e should fix it. Please do an ulnoiot upgrade, re-login or re-activate ulnoiot and see if now prompt changes properly, even if prompt_command was defined in advance.
